 pipeline {
    agent any
    stages {
        // stage('Stage 0: Checkout SCM'){
        //     steps{
        //         git branch: 'develop',
        //         credentialsId: 'codecommit-user',
        //         url: 'https://git-codecommit.us-east-1.amazonaws.com/v1/repos/todo-list-aws'
        //     }
        // }
        stage('Stage 1: Setup'){
            steps{
                    sh 'bash pipeline/PIPELINE-FULL-STAGING/1-setup.sh'  
            }
        }
        stage('Stage 2: Testing'){
            steps{
                    sh 'bash pipeline/PIPELINE-FULL-STAGING/2-testing.sh'
            }
        }
        stage('Stage 3: Build'){
            steps{
                    sh 'bash pipeline/PIPELINE-FULL-STAGING/3-package.sh'

            }
        }
        stage('Stage 4: Deploy'){
            steps{
                    sh 'bash pipeline/PIPELINE-FULL-STAGING/4-deploy.sh'
            }
        }
        stage('Stage 5: Integration Test'){
            steps{
                sh 'bash pipeline/PIPELINE-FULL-STAGING/5-integration.sh'
            }
        }
        stage('Stage 6: Clean up'){
            steps{
              deleteDir()      
            }
        }
    }
    post {
        // always{
        //     sh "docker rm -f dynamodb"
        // }
        failure {
            echo 'Bad news!!'
            //deleteDir()
        }
    }
}
